import type { WorkshopCard, WorkshopConfig } from "@/domain/types";

const cards: WorkshopCard[] = [
  {
    id: "atencion-ciudadania",
    phaseId: "justicia-actual",
    categoryId: "personas",
    title: "Mejora de la atención a la ciudadanía",
    shortDescription: "Una relación más accesible, clara y orientada a las necesidades reales.",
    challenge: "La ciudadanía demanda una atención más ágil, accesible y comprensible en sus relaciones con la Administración de Justicia.",
    solution: "Implantar un modelo de atención omnicanal, con servicios digitales intuitivos y apoyo presencial cuando sea necesario.",
    benefits: ["Mayor satisfacción ciudadana", "Reducción de tiempos de espera", "Acceso más equitativo a la justicia"],
    debateQuestion: "¿Qué cambios harían más cercana la Justicia valenciana?",
    order: 1,
  },
  {
    id: "bienestar-profesional",
    phaseId: "justicia-actual",
    categoryId: "personas",
    title: "Bienestar y desarrollo profesional",
    shortDescription: "Equipos preparados, cuidados y capaces de liderar el cambio.",
    challenge: "La presión operativa y el cambio continuo dificultan el aprendizaje y el bienestar de los equipos.",
    solution: "Crear itinerarios de capacitación, comunidades de práctica y medidas de apoyo organizativo adaptadas a cada función.",
    benefits: ["Mayor compromiso profesional", "Capacidades actualizadas", "Mejor adaptación al cambio"],
    debateQuestion: "¿Qué apoyo necesitan las personas para transformar la justicia de forma sostenible?",
    order: 2,
  },
  {
    id: "simplificacion-procesal",
    phaseId: "justicia-actual",
    categoryId: "procesos",
    title: "Simplificación procesal",
    shortDescription: "Procedimientos más claros y con menos cargas innecesarias.",
    challenge: "La complejidad de algunos circuitos genera demoras, duplicidades y una experiencia difícil de comprender.",
    solution: "Revisar los circuitos de extremo a extremo, eliminar pasos sin valor y unificar criterios operativos.",
    benefits: ["Menos tiempos de tramitación", "Menos tareas repetitivas", "Mayor previsibilidad"],
    debateQuestion: "¿Qué paso del proceso debería simplificarse primero y por qué?",
    order: 3,
  },
  {
    id: "coordinacion-organos",
    phaseId: "justicia-actual",
    categoryId: "procesos",
    title: "Coordinación entre órganos",
    shortDescription: "Circuitos compartidos para reducir esperas y derivaciones evitables.",
    challenge: "Las dependencias entre órganos y servicios no siempre son visibles ni se gestionan con criterios comunes.",
    solution: "Definir acuerdos de servicio, responsables claros y mecanismos regulares de coordinación y seguimiento.",
    benefits: ["Menos bloqueos entre unidades", "Resolución más fluida", "Responsabilidades claras"],
    debateQuestion: "¿Dónde aportaría más valor una coordinación transversal estable?",
    order: 4,
  },
  {
    id: "gestion-dato",
    phaseId: "justicia-actual",
    categoryId: "tecnologia",
    title: "Gestión del dato",
    shortDescription: "Datos fiables y compartidos para comprender y mejorar el servicio.",
    challenge: "La información se encuentra dispersa y no siempre tiene calidad o definiciones homogéneas.",
    solution: "Establecer un inventario de datos, criterios de calidad y cuadros de mando orientados a decisiones operativas.",
    benefits: ["Decisiones con evidencia", "Detección temprana de cuellos de botella", "Información coherente"],
    debateQuestion: "¿Qué dato ayudaría más a mejorar hoy el funcionamiento de la justicia?",
    order: 5,
  },
  {
    id: "herramientas-trabajo",
    phaseId: "justicia-actual",
    categoryId: "tecnologia",
    title: "Herramientas de trabajo integradas",
    shortDescription: "Un entorno digital sencillo que reduzca cambios de aplicación.",
    challenge: "El uso de herramientas fragmentadas aumenta la carga cognitiva y favorece errores de transcripción.",
    solution: "Priorizar integraciones y una experiencia de trabajo común alrededor de las tareas principales.",
    benefits: ["Menos duplicidad", "Mayor productividad", "Experiencia profesional más simple"],
    debateQuestion: "¿Qué tarea cotidiana debería poder resolverse desde un único entorno?",
    order: 6,
  },
  {
    id: "privacidad-dato",
    phaseId: "justicia-actual",
    categoryId: "gobernanza",
    title: "Seguridad y privacidad del dato",
    shortDescription: "Protección incorporada a procesos, decisiones y herramientas.",
    challenge: "La transformación digital amplía los riesgos sobre información sensible y exige responsabilidades claras.",
    solution: "Aplicar privacidad y seguridad desde el diseño, con controles proporcionados, formación y trazabilidad.",
    benefits: ["Mayor confianza", "Reducción de riesgos", "Uso responsable de la información"],
    debateQuestion: "¿Cómo equilibramos agilidad, acceso y protección de la información?",
    order: 7,
  },
  {
    id: "priorizacion-transparente",
    phaseId: "justicia-actual",
    categoryId: "gobernanza",
    title: "Priorización transparente",
    shortDescription: "Decisiones de mejora visibles, comparables y orientadas a valor público.",
    challenge: "Las iniciativas compiten por recursos sin un marco común para explicar su valor y urgencia.",
    solution: "Adoptar criterios públicos de priorización y revisar periódicamente resultados, riesgos y capacidad disponible.",
    benefits: ["Foco compartido", "Uso responsable de recursos", "Decisiones explicables"],
    debateQuestion: "¿Qué criterios deberían determinar qué mejora se aborda primero?",
    order: 8,
  },
  {
    id: "acompanamiento-digital",
    phaseId: "justicia-conectada",
    categoryId: "personas",
    title: "Acompañamiento digital inclusivo",
    shortDescription: "Canales digitales con apoyo para no dejar a nadie atrás.",
    challenge: "La digitalización puede aumentar barreras para personas con distintas capacidades o competencias digitales.",
    solution: "Combinar diseño accesible, lenguaje claro y puntos de acompañamiento humano durante los trámites digitales.",
    benefits: ["Inclusión efectiva", "Mayor autonomía", "Menos abandonos de trámite"],
    debateQuestion: "¿Qué apoyo evita que un canal digital se convierta en una nueva barrera?",
    order: 9,
  },
  {
    id: "colaboracion-profesional",
    phaseId: "justicia-conectada",
    categoryId: "personas",
    title: "Colaboración profesional en red",
    shortDescription: "Conocimiento compartido entre perfiles, sedes y disciplinas.",
    challenge: "Las buenas prácticas quedan aisladas y el conocimiento depende demasiado de relaciones informales.",
    solution: "Crear comunidades de práctica y espacios seguros para compartir criterios, recursos y aprendizajes.",
    benefits: ["Aprendizaje más rápido", "Criterios más coherentes", "Mejor resolución de problemas"],
    debateQuestion: "¿Qué conocimiento deberíamos compartir de forma sistemática?",
    order: 10,
  },
  {
    id: "expediente-interoperable",
    phaseId: "justicia-conectada",
    categoryId: "procesos",
    title: "Expediente interoperable",
    shortDescription: "Información disponible donde se necesita, sin duplicar gestiones.",
    challenge: "La fragmentación obliga a repetir aportaciones y dificulta una visión completa de la tramitación.",
    solution: "Definir intercambios normalizados y responsabilidades para compartir información pertinente entre sistemas autorizados.",
    benefits: ["Menos duplicidades", "Continuidad de la tramitación", "Información más consistente"],
    debateQuestion: "¿Qué intercambio de información eliminaría más fricción entre servicios?",
    order: 11,
  },
  {
    id: "derivacion-coordinada",
    phaseId: "justicia-conectada",
    categoryId: "procesos",
    title: "Derivación coordinada de servicios",
    shortDescription: "Transiciones claras entre justicia y servicios de apoyo.",
    challenge: "Las personas pueden perderse entre administraciones y servicios cuando una necesidad requiere varias respuestas.",
    solution: "Diseñar protocolos de derivación con información mínima compartida, seguimiento y puntos de contacto claros.",
    benefits: ["Atención más integral", "Menos repeticiones", "Mayor continuidad"],
    debateQuestion: "¿Qué derivación requiere hoy una coordinación más clara?",
    order: 12,
  },
  {
    id: "notificaciones-unificadas",
    phaseId: "justicia-conectada",
    categoryId: "tecnologia",
    title: "Notificaciones unificadas",
    shortDescription: "Comunicaciones trazables y comprensibles desde un punto común.",
    challenge: "La diversidad de canales y formatos dificulta saber qué comunicación requiere atención y cuándo.",
    solution: "Ofrecer un centro de notificaciones con preferencias accesibles, lenguaje claro y trazabilidad.",
    benefits: ["Menos comunicaciones perdidas", "Mayor comprensión", "Trazabilidad compartida"],
    debateQuestion: "¿Cómo debería ser una notificación judicial realmente útil?",
    order: 13,
  },
  {
    id: "servicios-digitales-comunes",
    phaseId: "justicia-conectada",
    categoryId: "tecnologia",
    title: "Servicios digitales comunes",
    shortDescription: "Capacidades reutilizables para evitar soluciones aisladas.",
    challenge: "Resolver repetidamente necesidades similares aumenta costes y produce experiencias inconsistentes.",
    solution: "Construir servicios compartidos de identidad, firma, consulta y comunicación con interfaces comunes.",
    benefits: ["Reutilización", "Experiencia coherente", "Evolución más sostenible"],
    debateQuestion: "¿Qué capacidad común tendría mayor impacto si se reutilizara?",
    order: 14,
  },
  {
    id: "estandares-interoperabilidad",
    phaseId: "justicia-conectada",
    categoryId: "gobernanza",
    title: "Estándares de interoperabilidad",
    shortDescription: "Reglas comunes para conectar servicios con seguridad y sentido.",
    challenge: "Las conexiones puntuales son frágiles cuando no comparten modelos, responsabilidades y criterios de evolución.",
    solution: "Acordar estándares técnicos y semánticos, gobierno de cambios y pruebas de conformidad.",
    benefits: ["Integraciones sostenibles", "Menos ambigüedad", "Mayor capacidad de evolución"],
    debateQuestion: "¿Qué estándar común desbloquearía más colaboración?",
    order: 15,
  },
  {
    id: "gobierno-ecosistema",
    phaseId: "justicia-conectada",
    categoryId: "gobernanza",
    title: "Gobierno del ecosistema",
    shortDescription: "Decisiones compartidas entre las organizaciones conectadas.",
    challenge: "La interoperabilidad falla si cada parte optimiza solo su sistema y no existe una visión conjunta.",
    solution: "Establecer órganos de decisión, métricas comunes y mecanismos de resolución de dependencias.",
    benefits: ["Responsabilidad compartida", "Decisiones más rápidas", "Objetivos alineados"],
    debateQuestion: "¿Qué decisiones deben gobernarse de forma conjunta?",
    order: 16,
  },
  {
    id: "asistencia-profesional",
    phaseId: "justicia-inteligente",
    categoryId: "personas",
    title: "Asistencia inteligente al profesional",
    shortDescription: "Apoyo a tareas repetitivas sin sustituir el criterio experto.",
    challenge: "El tiempo profesional se consume en localizar, ordenar y preparar información para tareas de mayor valor.",
    solution: "Introducir asistentes supervisados que ayuden a resumir, comprobar y preparar información con trazabilidad.",
    benefits: ["Más tiempo para el criterio experto", "Menos carga repetitiva", "Trabajo más consistente"],
    debateQuestion: "¿Qué tarea podría asistirse manteniendo siempre la decisión humana?",
    order: 17,
  },
  {
    id: "competencias-ia",
    phaseId: "justicia-inteligente",
    categoryId: "personas",
    title: "Competencias para una justicia inteligente",
    shortDescription: "Capacidad crítica para usar y supervisar nuevas herramientas.",
    challenge: "La adopción tecnológica sin comprensión suficiente puede generar dependencia, errores y pérdida de confianza.",
    solution: "Desarrollar alfabetización en datos e IA, criterios de uso y entrenamiento práctico por perfiles.",
    benefits: ["Uso responsable", "Mayor autonomía profesional", "Mejor detección de errores"],
    debateQuestion: "¿Qué competencia será imprescindible para supervisar herramientas inteligentes?",
    order: 18,
  },
  {
    id: "triaje-asistido",
    phaseId: "justicia-inteligente",
    categoryId: "procesos",
    title: "Triaje asistido y supervisado",
    shortDescription: "Clasificación inicial consistente con control humano.",
    challenge: "La identificación manual de necesidades y prioridades consume tiempo y puede aplicar criterios distintos.",
    solution: "Asistir la clasificación inicial con reglas explícitas, revisión humana y canales de corrección.",
    benefits: ["Respuesta inicial más ágil", "Criterios visibles", "Mejor asignación de recursos"],
    debateQuestion: "¿Qué garantías debe tener un sistema de triaje asistido?",
    order: 19,
  },
  {
    id: "prevencion-cuello-botella",
    phaseId: "justicia-inteligente",
    categoryId: "procesos",
    title: "Prevención de cuellos de botella",
    shortDescription: "Anticipación operativa para actuar antes de que crezcan las demoras.",
    challenge: "Los problemas de capacidad suelen hacerse visibles cuando ya afectan a muchas tramitaciones.",
    solution: "Combinar señales operativas y revisión experta para detectar tendencias y activar respuestas proporcionadas.",
    benefits: ["Intervención temprana", "Mejor planificación", "Menos acumulación de trabajo"],
    debateQuestion: "¿Qué señal temprana permitiría anticipar una demora relevante?",
    order: 20,
  },
  {
    id: "calidad-automatizacion",
    phaseId: "justicia-inteligente",
    categoryId: "tecnologia",
    title: "Automatización con control de calidad",
    shortDescription: "Automatizar tareas verificables con supervisión y reversibilidad.",
    challenge: "Una automatización opaca o difícil de corregir puede escalar errores y reducir la confianza.",
    solution: "Priorizar tareas acotadas, registrar resultados, medir errores y asegurar revisión y reversión humanas.",
    benefits: ["Ahorro de tiempo", "Resultados verificables", "Mejora continua"],
    debateQuestion: "¿Qué tarea reúne hoy las condiciones para automatizarse de forma segura?",
    order: 21,
  },
  {
    id: "analitica-explicable",
    phaseId: "justicia-inteligente",
    categoryId: "tecnologia",
    title: "Analítica explicable",
    shortDescription: "Patrones útiles sin convertir correlaciones en decisiones automáticas.",
    challenge: "Los análisis complejos pierden utilidad y legitimidad si no pueden comprenderse, cuestionarse y contextualizarse.",
    solution: "Ofrecer indicadores interpretables, límites conocidos, fuentes trazables y revisión experta de conclusiones.",
    benefits: ["Decisiones informadas", "Resultados auditables", "Mayor confianza"],
    debateQuestion: "¿Qué explicación mínima necesitamos antes de usar una recomendación analítica?",
    order: 22,
  },
  {
    id: "gobierno-algoritmico",
    phaseId: "justicia-inteligente",
    categoryId: "gobernanza",
    title: "Gobierno algorítmico responsable",
    shortDescription: "Reglas, responsables y supervisión para cada sistema inteligente.",
    challenge: "Los sistemas inteligentes introducen riesgos nuevos que no se resuelven solo con controles técnicos.",
    solution: "Definir inventario, responsables, evaluación de impacto, supervisión, reclamación y retirada segura.",
    benefits: ["Responsabilidad clara", "Riesgos controlados", "Confianza institucional"],
    debateQuestion: "¿Qué condición debería impedir desplegar un sistema inteligente?",
    order: 23,
  },
  {
    id: "transparencia-decisiones",
    phaseId: "justicia-inteligente",
    categoryId: "gobernanza",
    title: "Transparencia de decisiones asistidas",
    shortDescription: "Que las personas sepan cuándo y cómo interviene la tecnología.",
    challenge: "La intervención de sistemas automatizados puede quedar invisible para quienes reciben o revisan una actuación.",
    solution: "Informar del uso, alcance y límites de la asistencia, conservando trazabilidad y vías de revisión humana.",
    benefits: ["Derecho a comprender", "Mayor capacidad de revisión", "Legitimidad del servicio"],
    debateQuestion: "¿Qué información debe recibir una persona ante una decisión asistida?",
    order: 24,
  },
];

export const workshopConfig: WorkshopConfig = {
  title: "Justicia 2030",
  intro: "Explora las etapas del workshop, debate las propuestas y selecciona tres tarjetas por etapa para construir una visión compartida de la Justicia 2030.",
  maxSelectionsPerPhase: 3,
  collectives: [
    { id: "colectivo-a", name: "Colectivo A", description: "Una mirada centrada en las personas y en el acceso claro a la justicia." },
    { id: "colectivo-b", name: "Colectivo B", description: "Una mirada que conecta equipos, conocimiento y servicios públicos." },
    { id: "colectivo-c", name: "Colectivo C", description: "Una mirada orientada a transformar procesos con datos y tecnología." },
    { id: "colectivo-d", name: "Colectivo D", description: "Una mirada que equilibra innovación, garantías y confianza." },
  ],
  phases: [
    { id: "justicia-actual", name: "Justicia Actual", shortName: "Actual", description: "Comprender y mejorar la situación de partida.", order: 1, accent: "orange" },
    { id: "justicia-conectada", name: "Justicia Conectada", shortName: "Conectada", description: "Conectar capacidades, servicios y conocimiento.", order: 2, accent: "green" },
    { id: "justicia-inteligente", name: "Justicia Inteligente", shortName: "Inteligente", description: "Usar datos y tecnología con criterio y garantías.", order: 3, accent: "blue" },
  ],
  categories: [
    { id: "personas", name: "Personas", order: 1 },
    { id: "procesos", name: "Procesos", order: 2 },
    { id: "tecnologia", name: "Tecnología", order: 3 },
    { id: "gobernanza", name: "Gobernanza", order: 4 },
  ],
  cards,
};

export const storageKeys = {
  team: "justicia2030:v1:team",
  facilitator: "justicia2030:v1:facilitator",
} as const;
